/*
 * Serviço de Livros
 * Esta é a descrição de API do nosso serviço de registro de livros.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.douglas.livros.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * InlineObject1
 */
@JsonPropertyOrder({
  InlineObject1.JSON_PROPERTY_CODIGO,
  InlineObject1.JSON_PROPERTY_TITULO,
  InlineObject1.JSON_PROPERTY_AUTOR,
  InlineObject1.JSON_PROPERTY_N_PAGINAS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-26T17:36:30.699353-03:00[America/Sao_Paulo]")
public class InlineObject1 {
  public static final String JSON_PROPERTY_CODIGO = "codigo";
  private String codigo;

  public static final String JSON_PROPERTY_TITULO = "titulo";
  private String titulo;

  public static final String JSON_PROPERTY_AUTOR = "autor";
  private String autor;

  public static final String JSON_PROPERTY_N_PAGINAS = "n_paginas";
  private String nPaginas;


  public InlineObject1 codigo(String codigo) {
    
    this.codigo = codigo;
    return this;
  }

   /**
   * Get codigo
   * @return codigo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CODIGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodigo() {
    return codigo;
  }


  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }


  public InlineObject1 titulo(String titulo) {
    
    this.titulo = titulo;
    return this;
  }

   /**
   * Get titulo
   * @return titulo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TITULO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitulo() {
    return titulo;
  }


  public void setTitulo(String titulo) {
    this.titulo = titulo;
  }


  public InlineObject1 autor(String autor) {
    
    this.autor = autor;
    return this;
  }

   /**
   * Get autor
   * @return autor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAutor() {
    return autor;
  }


  public void setAutor(String autor) {
    this.autor = autor;
  }


  public InlineObject1 nPaginas(String nPaginas) {
    
    this.nPaginas = nPaginas;
    return this;
  }

   /**
   * Get nPaginas
   * @return nPaginas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_N_PAGINAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getnPaginas() {
    return nPaginas;
  }


  public void setnPaginas(String nPaginas) {
    this.nPaginas = nPaginas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject1 inlineObject1 = (InlineObject1) o;
    return Objects.equals(this.codigo, inlineObject1.codigo) &&
        Objects.equals(this.titulo, inlineObject1.titulo) &&
        Objects.equals(this.autor, inlineObject1.autor) &&
        Objects.equals(this.nPaginas, inlineObject1.nPaginas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, titulo, autor, nPaginas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject1 {\n");
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    titulo: ").append(toIndentedString(titulo)).append("\n");
    sb.append("    autor: ").append(toIndentedString(autor)).append("\n");
    sb.append("    nPaginas: ").append(toIndentedString(nPaginas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

