/*
 * Serviço de Livros
 * Esta é a descrição de API do nosso serviço de registro de livros.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.douglas.livros.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineObject
 */
public class InlineObjectTest {
    private final InlineObject model = new InlineObject();

    /**
     * Model tests for InlineObject
     */
    @Test
    public void testInlineObject() {
        // TODO: test InlineObject
    }

    /**
     * Test the property 'codigo'
     */
    @Test
    public void codigoTest() {
        // TODO: test codigo
    }

    /**
     * Test the property 'titulo'
     */
    @Test
    public void tituloTest() {
        // TODO: test titulo
    }

    /**
     * Test the property 'autor'
     */
    @Test
    public void autorTest() {
        // TODO: test autor
    }

    /**
     * Test the property 'nPaginas'
     */
    @Test
    public void nPaginasTest() {
        // TODO: test nPaginas
    }

}
