/*
 * Serviço de Livros
 * Esta é a descrição de API do nosso serviço de registro de livros.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.douglas.livros_service.api;

import com.douglas.livros.model.InlineObject;
import com.douglas.livros.model.InlineObject1;
import com.douglas.livros.model.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LivroApi
 */
@Ignore
public class LivroApiTest {

    private final LivroApi api = new LivroApi();

    
    /**
     * Atualiza os dados de um livro
     *
     * Atualiza os dados de um livro pelo código
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void atualizarLivroTest() {
        String codigo = null;
        InlineObject1 body = null;
        api.atualizarLivro(codigo, body);

        // TODO: test validations
    }
    
    /**
     * Buscar livro por código
     *
     * Retorna o livro pelo código
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void buscarPorCodigoTest() {
        Long codigo = null;
        InlineResponse200 response = api.buscarPorCodigo(codigo);

        // TODO: test validations
    }
    
    /**
     * Cadastrar um novo livro
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void criarLivroTest() {
        InlineObject body = null;
        api.criarLivro(body);

        // TODO: test validations
    }
    
    /**
     * Listar todos os livros
     *
     * Retorna a lista de livros do sistema
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listarLivrosTest() {
        List<InlineResponse200> response = api.listarLivros();

        // TODO: test validations
    }
    
    /**
     * Exclui um livro
     *
     * Apaga um livro pelo código
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeLivroTest() {
        Integer codigo = null;
        api.removeLivro(codigo);

        // TODO: test validations
    }
    
}
